---
title: "Chapter 3 Exercise Review"
date: "2025-02-06"
categories: [study]
---

## 3.1.

**식(3.29) 모형의 표준편차가** $y$의 기댓값에 비례하는 지 보이라.

$$
\mathrm{log}\ y_i \sim \mathrm{indep}. \mathcal{N}(\alpha^* + \beta^*x_i,\ \sigma^{*2}), \quad i = 1,2,\cdots,N, \quad (3.29)
$$

-   로그 정규 분포$y \sim \mathrm{log}N(\mu,\sigma^2)$는 다음과 같다.

$$
\begin{aligned}
E(y) &= \mathrm{exp}(\mu + \frac{1}{2}\sigma^2),\\
Var(y) &= (\mathrm{exp}(\sigma^2)-1)\mathrm{exp}(2\mu + \sigma^2)\\
\end{aligned}
$$

-   이것을 (3.29)모형에 적용하면 다음과 같다.

$$
\begin{aligned}
E(y_i) &= \mathrm{exp}(\alpha^*+\beta^*x_i+\frac{1}{2}\sigma^{*2})\\
Var(y_i) &= (\mathrm{exp}(\sigma^{*2})-1)\mathrm{exp}(2(\alpha^*+\beta^*x_i)+\sigma^{*2})\\
&= (\mathrm{exp}(\sigma^{*2})-1)E(y_i)^2\\
\end{aligned}
$$

$y_i$의 표준편차는 $\sqrt{\mathrm{exp}(\sigma^{*2}-1)}$를 상수로 두고 $y_i$의 기댓값에 비례한다는 것을 알 수 있다.

# Random intercepts: Balanced Data Section

## 3.2.

**Section 3.5b-i 에** $\hat{\mu},\hat{\beta}$(3.58,59)식을 상세하게 전개해라.

(3.52)식을 정리하면 된다 (3.53,56,57)식은 다음과 같다.

$$
\begin{aligned}
& \begin{bmatrix} 
\hat{\mu} \\ 
\hat{\beta} 
\end{bmatrix}
=
\left[ \frac{1}{m} \otimes \left( \mathbf{X}_0' \mathbf{V}_0^{-1} \mathbf{X}_0 \right)^{-1} \right]
\left( \mathbf{1}_m' \otimes \mathbf{X}_0' \mathbf{V}_0^{-1} \right) \mathbf{y}, \quad & (3.52) \\
\\
& \mathbf{X}_0' \mathbf{V}_0^{-1} = 
\begin{bmatrix}
\mathbf{1}_n' \\
\mathbf{x}_0'
\end{bmatrix}
\frac{1}{\sigma^2} (\mathbf{I}_n - \tau \mathbf{\bar{J}}_n) 
= 
\begin{bmatrix}
\frac{\tau}{n\sigma_a^2} \mathbf{1}_n' \\
(\mathbf{x}_0' - \tau \bar{x_.} \mathbf{1}_n') / \sigma^2
\end{bmatrix}, \quad & (3.53) \\
\\
& ( \mathbf{1}_m' \otimes \mathbf{X}_0' \mathbf{V}_0^{-1} ) \mathbf{y} = 
\left( \frac{m\tau}{\sigma_a^2} \right)
\begin{bmatrix}
\bar{y}_{..} \\
S_{xy} \frac{\sigma_a^2}{\tau \sigma^2} + \bar{x_.} \bar{y_{..}}
\end{bmatrix}, \quad & (3.56) \\
\\
& ( \mathbf{X}_0' \mathbf{V}_0^{-1} \mathbf{X}_0 )^{-1} = 
\frac{\sigma^2}{S_{xx}}
\begin{bmatrix}
S_{xx} \frac{\sigma_a^2}{\tau \sigma^2} + \bar{x_.}^2 & -\bar{x_.} \\
- \bar{x_.} & 1
\end{bmatrix}, \quad & (3.57)
\end{aligned}
$$

#### 1. $\left[ \frac{1}{m} \otimes \left( \mathbf{X}_0' \mathbf{V}_0^{-1} \mathbf{X}_0 \right)^{-1} \right]$

::: callout-tip
크로노커 곱(Kronecker product)이 있어서 어려워보이지만 $\frac{1}{m}$이 벡터가 아닌 스칼라이기에 그냥 스칼라 곱을 하면 된다.
:::

-   즉, 다음과 같고 이 행렬의 차원은 $2\times2$이다.

$$
\frac{1}{m} \otimes \left( \mathbf{X}_0' \mathbf{V}_0^{-1} \mathbf{X}_0 \right)^{-1} = \frac{1}{m} \frac{\sigma^2}{S_{xx}}
\begin{bmatrix}
S_{xx} \frac{\sigma_a^2}{\tau \sigma^2} + \bar{x_.}^2 & -\bar{x_.} \\
- \bar{x_.} & 1
\end{bmatrix}
$$

#### 2. $\left( \mathbf{1}_m' \otimes \mathbf{X}_0' \mathbf{V}_0^{-1} \right) \mathbf{y}$

::: callout-tip
$\left( \mathbf{1}_m' \otimes \mathbf{X}_0' \mathbf{V}_0^{-1} \right) \mathbf{y}$부분에서 $\mathbf{1}_m' \otimes \mathbf{X}_0' \mathbf{V}_0^{-1}$부분을 살펴보면 $\mathbf{X}_0' \mathbf{V}_0^{-1}$ 행렬이 행벡터처럼 m개 있는 형태를 갖는다.
:::

-   차원의 형태는 $2\times mn$ 이다.

$$
\mathbf{1}_m' \otimes \mathbf{X}_0' \mathbf{V}_0^{-1} = \left[\mathbf{X}_0' \mathbf{V}_0^{-1},\ \mathbf{X}_0' \mathbf{V}_0^{-1},\cdots,\mathbf{X}_0' \mathbf{V}_0^{-1}\right]
$$

#### 3. $\left[ \frac{1}{m} \otimes \left( \mathbf{X}_0' \mathbf{V}_0^{-1} \mathbf{X}_0 \right)^{-1} \right] \left( \mathbf{1}_m' \otimes \mathbf{X}_0' \mathbf{V}_0^{-1} \right) \mathbf{y}$

-   이제 최종곱을 해보자

-   그 전에 계산의 편의를 위해$c:= \frac{\sigma^2}{mS_{xx}}, d:=\frac{m\tau}{\sigma^2_a}$라 하자.

##### $\hat{\beta}$

-   $\hat{\beta}$부터 계산해보자.

$$
\begin{aligned}
\hat{\beta} &= cd\left[-\bar{x}_.\bar{y}_{..} + \left(S_{xy}\frac{\sigma^2_a}{\tau\sigma^2} + \bar{x}_.\bar{y}_{..}\right)\right]\\
&= \frac{\sigma^2}{mS_{xx}}\frac{m\tau}{\sigma^2_a}\left[S_{xy}\frac{\sigma^2_a}{\tau\sigma^2}\right]\\
&= \frac{S_{xy}}{S_{xx}}
\end{aligned}
$$

##### $\hat{\mu}$

-   $\hat{\mu}$을 계산해보자.

$$
\begin{aligned}
\hat\mu &= cd\left[\left(S_{xx}\frac{\sigma^2_a}{\tau\sigma^2}+\bar{x}_.^2\right)\bar{y}_{..} - \bar{x}\left(S_{xy}\frac{\sigma^2_a}{\tau\sigma^2} +\bar{x}_. \bar{y}_{..}\right)\right]\\
\
&= cd \frac{\sigma^2_a}{\tau\sigma^2} \left[S_{xx}\ \bar{y_{..}} - \bar{x}_.S_{xy}\right]\\
\
& = \frac{\sigma^2}{mS_{xx}}\frac{m\tau}{\sigma^2_a}\frac{\sigma^2_a}{\tau\sigma^2}\left[S_{xx}\ \bar{y_{..}} - \bar{x}_.S_{xy}\right]\\
\
& = \frac{1}{S_{xx}}\left[S_{xx}\ \bar{y_{..}} - \bar{x}_.S_{xy}\right]\\
\
& = \bar{y}_{..} - \frac{\bar{x}_.S_{xy}}{S_{xx}} = \bar{y}_{..} - \hat{\beta}\bar{x}_.
\end{aligned}
$$

## 3.3

**(3.65)식을 유도하고 그 다음 75,76식도 유도하기**

### (3.65)식

-   식(3.65)는 $mn$차원인 $\pmb{y}$의 다변량 정규분포를 로그 가능도함수로 만들어주면 된다.

-   다변량 정규분포의 가능도함수는 다음과 같다.

$$
L=\frac{\exp \left\{-\frac{1}{2}(\mathbf{y}-\boldsymbol{\theta})^{\prime} \mathbf{V}^{-1}(\mathbf{y}-\boldsymbol{\theta})\right\}}{(2 \pi)^{\frac{m n}{2}}|\mathbf{V}|^{\frac{1}{2}}}
$$

-   위 식에 로그를 입히면 다음과 같다.

$$
l=\ln L=-\frac{1}{2}\left[m n \ln (2 \pi)+\ln |\pmb{V}|+\left(\pmb{y}-\pmb{X}[\mu, \beta]^{\prime}\right)^{\prime} \pmb{V}^{-1}\left(\pmb{y}-\pmb{X}[\mu, \beta]^{\prime}\right)\right]
$$

-   괄호안에 전개해야 할 식들을 각각 알아보자.

#### 1. $\ln|\pmb{V}|$

-   $|\pmb{V}|^{\frac{1}{2}}$이 다음과 같으므로 $|\pmb{V}|^{\frac{1}{2}}=\left|\pmb{V}_0\right|^{\frac{1}{2} m}=\sigma^{2 \frac{m(n-1)}{2}}\left(\sigma^2+n \sigma_a^2\right)^{\frac{m}{2}}$

-   $\ln|\pmb{V}|$을 다음과 같이 정리 할수 있다.

$$
\ln |\pmb{V}|=m(n-1) \ln \left(\sigma^2\right)+m \ln \left(\sigma^2+n \sigma_a^2\right).
$$

#### 2. $\left(\pmb{y}-\pmb{X}[\mu, \beta]^{\prime}\right)^{\prime} \pmb{V}^{-1}\left(\pmb{y}-\pmb{X}[\mu, \beta]^{\prime}\right)$

::: callout-tip
우선, $[\mu, \beta]$부분을 $[\hat{\mu}, \hat{\beta}]$으로 대입할 것이고 계산의 편의를 위해 $\hat{\pmb{\theta}}$으로 바꾼다.

또한, $mn$차원의 벡터이지만 $m$번 반복했기 때문에 간단하게 보일 필요가 있다.
:::

그럼, 다음과 같다.

$$
\left(\pmb{y}-\pmb{X}\hat{\pmb{\theta}}\right)^{\prime} \pmb{V}^{-1}\left(\pmb{y}-\pmb{X}\hat{\pmb{\theta}}\right)
=\sum^m_{i=1}\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)^{\prime} \pmb{V}_0^{-1}\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)
$$

##### 1. $\pmb{V}_0^{-1}$

-   공분산 행렬을 풀어보면 다음과 같다(책 본문에 나와있음)

$$
\pmb{V}_0^{-1}=\frac{1}{\sigma^2}\Big[\pmb{I}_n-\underbrace{\frac{\sigma_a^2}{\sigma^2+n \sigma_a^2}}_{=: \tau} \pmb{J}_n\Big] .
$$

-   풀어진 $\pmb{V}_0^{-1}$을 대입해서 다시보면 다음과 같다.

$$
\sum^m_{i=1}\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)^{\prime} \pmb{V}_0^{-1}\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right) 
= \sum^m_{i=1}\frac{1}{\sigma^2}\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)^{\prime}\Big[\pmb{I}_n-\tau \pmb{J}_n\Big]\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right) 
$$

##### 2. $\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)^{\prime}\Big[\pmb{I}_n\Big]\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)$

-   이 부분에 해당하는 2차 행렬식부터 살펴보자.

-   $r_{ij} = y_{ij} - \hat{\mu} - \hat{\beta}x_j$ 라고 두면, $\pmb{y}_i - \pmb{X}_0 \hat{\pmb\theta}$는 $n$차원 벡터인 $(r_{i1},\cdots,r_{in})^\prime$로 둘수 있다.

그럼,

$$
(\pmb{y}_i - \pmb{X}_0 \hat{\pmb\theta})^{\prime}(\pmb{y}_i - \pmb{X}_0 \hat{\pmb\theta}) = \sum^n_{j=1}r_{ij}^2
$$

##### 3. $-\tau\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)^{\prime}\Big[\pmb{J}_n\Big]\left(\pmb{y}_i-\pmb{X}_0\hat{\pmb{\theta}}\right)$

-   직접 식을 계산해보면 어렵지 않게 구할 수 있다.

$$
-\tau\left(\pmb{y}_i-\pmb{X}_0 \hat{\pmb{\theta}}\right)^{\prime} \pmb{J}_n\left(\pmb{y}_i-\pmb{X}_0 \hat{\pmb{\theta}}\right)=-\tau\left(\sum_{j=1}^n r_{i j}\right)^2=-\tau n^2\left(\bar{y}_i-\hat{\mu}-\hat{\beta} \bar{x}_.\right)^2
$$

그래서 정리하면 다음과 같다.

$$
\sum_{i=1}^m\left(\pmb{y}_i-\pmb{X}_0 \hat{\theta}\right)^{\prime} \pmb{V}_0^{-1}\left(\pmb{y}_i-\pmb{X}_0 \hat{\pmb{\theta}}\right)
=\frac{1}{\sigma^2}\left[\sum_{i, j} r_{i j}^2-\tau n^2 \sum_i\left(\bar{y}_{i .}-\hat{\mu}-\hat{\beta} \bar{x}_.\right)^2\right]
$$

##### 4. Rewrite in terms of $S_1$ and $S_2$

-   주어진 $S_1,S_2$로 변환을 해준다.

참고로,

$$
\text{S}_1=\sum_{i, j}\left[y_{i j}-\hat{\mu}-\hat{\beta} x_j\right]^2, \quad
\text{S}_2=\sum_i n\left(\bar{y}_i-\hat{\mu}-\hat{\beta} \bar{x}\right)^2
$$

변환을 해주면 이제 문제에서 원하는 식의 형태를 갖추게 된다.

$$
(\boldsymbol{y}-\boldsymbol{X} \hat{\boldsymbol{\theta}})^{\prime} \boldsymbol{V}^{-1}(\boldsymbol{y}-\boldsymbol{X} \hat{\boldsymbol{\theta}})=\frac{1}{\sigma^2} \text{S}_1-\frac{\tau n}{\sigma^2}\text{S}_2=\frac{\text{S}_1}{\sigma^2}-\frac{n \sigma_a^2}{\sigma^2\left(\sigma^2+n \sigma_a^2\right)} \text{S}_2
$$

#### 3. 정리

-   정리하면 식 3.65와 같이 표현할 수 있다. (책의 notation과 다름)

$$
l^*=-\frac{1}{2}\left[m n \log (2 \pi)+m(n-1) \log \left(\sigma^2\right)+m \log \left(\sigma^2+n \sigma_a^2\right)+\frac{\text{S}_1}{\sigma^2}-\frac{n \sigma_a^2 \text{S}_2}{\sigma^2\left[\sigma^2+n \sigma_a^2\right]}\right]
$$

### (3.75)식

**(3.65)를** $\sigma^2_a$로 미분해서 추정량을 구해보자

$$
\begin{aligned} 
\frac{\partial \ l^*}{\partial \sigma^2_a} & = -\frac{1}{2} \left[\frac{mn}{\sigma^2 + n \sigma^2_a} - \frac{n \text{S}_2\sigma^2(\sigma^2+n\sigma_a^2)-n^2\sigma^2\sigma_a^2\text{S}_2}{(\sigma^2)^2(\sigma^2+n\sigma^2_a)^2}\right] \\
& = -\frac{1}{2} \left[\frac{mn}{\sigma^2 + n \sigma^2_a} - \frac{n \text{S}_2(\sigma^2)^2+n^2\sigma^2\sigma_a^2\text{S}_2-n^2\sigma^2\sigma_a^2\text{S}_2}{(\sigma^2)^2(\sigma^2+n\sigma^2_a)^2}\right]\\
& = -\frac{1}{2} \left[\frac{mn}{\sigma^2 + n \sigma^2_a} - \frac{n \text{S}_2(\sigma^2)^2}{(\sigma^2+n\sigma^2_a)^2}\right] = 0 \\
\\
\Rightarrow & \ \sigma^2 + n\sigma_a^2 = \frac{\text{S}_2}{m} = \frac{\text{SSA}}{m} \quad \quad \quad \quad \quad \quad \quad \quad (3.75)\\
\\
\because \quad \text{S}_2 & =\sum_i n\left(\bar{y}_{i \cdot}-\hat{\mu}-\hat{\beta} \bar{x}_.\right)^2 \quad \text{input }\hat{\mu}\text{ in }\text{S}_2,\\
& = \sum_{i=1}^m n\left[\bar{y}_{i.}-\bar{y}_{. .}-\hat{\beta}(\bar{x}_.-\bar{x}_.)\right]^2=\sum_{i=1}^m n\left(\bar{y}_{i.}-\bar{y}_{..}\right)^2=\text{SSA}\\
\end{aligned}
$$

### (3.76) 식

**(3.65)를** $\sigma^2$로 미분해서 추정량을 정리하자. 단, (3.75)식을 적용하자.

$$
\begin{aligned}
\frac{\partial \ l^*}{\partial \sigma^2} &= -\frac{1}{2}\left[\frac{m(n-1)}{\sigma^2} + \frac{m}{\sigma^2 + n\sigma^2_a} - \frac{\text{S}_1}{(\sigma^2)^2} + \frac{n\sigma^2_a\ \text{S}_2(2\sigma^2+n\sigma^2_a)}{(\sigma^2)^2(\sigma^2+n\sigma^2_a)^2}\right] \\
&= -\frac{1}{2}\left[\frac{m(n-1)}{\sigma^2} + \frac{m^2}{\text{SSA}} - \frac{\text{S}_1}{(\sigma^2)^2} + \frac{n\sigma^2_a\ \text{SSA}(\sigma^2+\frac{\text{SSA}}{m})}{(\sigma^2)^2(\frac{\text{SSA}}{m})^2}\right] \quad \because \text{input }\ \sigma^2+n\sigma^2_a = \frac{\text{SSA}}{m}\\
&= -\frac{1}{2}\left[\frac{m(n-1)}{\sigma^2} + \frac{m^2}{\text{SSA}} - \frac{\text{S}_1}{(\sigma^2)^2} + \frac{m^2n\ \sigma_a^2\ \sigma^2 + mn\ \sigma_a^2\ \text{SSA}}{(\sigma^2)^2\ \text{SSA}}\right] \\
& = -\frac{1}{2}\left[\frac{m(n-1)}{\sigma^2} + \frac{m^2}{\text{SSA}} - \frac{\text{S}_1}{(\sigma^2)^2} + \frac{m^2n\ \sigma_a^2}{\sigma^2 \text{SSA}} + \frac{mn\ \sigma_a^2}{(\sigma^2)^2}\right] \\
& = -\frac{1}{2}\left[\frac{m(n-1)}{\sigma^2} + \frac{m^2(\sigma^2+n\sigma_a^2)}{\text{SSA}\ \sigma^2} + \frac{mn\ \sigma_a^2-\text{S}_1}{(\sigma^2)^2} \right] \\
& = -\frac{1}{2}\left[\frac{m(n-1)}{\sigma^2} + \frac{m^2(\frac{\text{SSA}}{m})}{\text{SSA}\ \sigma^2} + \frac{mn\ \sigma_a^2-\text{S}_1}{(\sigma^2)^2} \right] \\
& = -\frac{1}{2}\left[\frac{m(n-1)}{\sigma^2} + \frac{m}{\sigma^2} + \frac{mn\ \sigma_a^2-\text{S}_1}{(\sigma^2)^2} \right] = 0 \\
\\
\Rightarrow & \ mn\ \sigma^2 + mn\ \sigma_a^2 = \text{S}_1 \\
\Rightarrow & \ mn\ \sigma^2 + mn\ \frac{1}{n}\left(\frac{\text{SSA}}{m}-\sigma^2\right) \quad \quad \quad \quad \quad \quad \because \sigma_a^2 = \frac{1}{n}\left(\frac{\text{SSA}}{m}-\sigma^2\right)\\
& = \text{SSA} + m(n-1)\sigma^2 = \text{SST} - \hat{\beta}^2 m \text{S}_{xx} \quad \quad \because \text{S}_1 = \text{SST} - \hat{\beta}^2 m \text{S}_{xx} \\
\Rightarrow & \ m(n-1)\sigma^2 = \text{SSE} - \hat{\beta}^2 m \text{S}_{xx} \\
\Rightarrow & \ \therefore \sigma^2 = \frac{\text{SSE} - \hat{\beta}^2 m \text{S}_{xx}}{m(n-1)} = \frac{\text{SSR}}{m(n-1)}\\
\end{aligned}
$$

## 3.4

$\hat{\sigma}^2_a=0$일 때, $H:\sigma^2_a=0$의 LR통계량이 1인 것은 어떤 의미인가.

-   LR 검정을 하려면 우선 식은 다음과 같다.

-   $\hat{\sigma}_a^2=0$라는 것은, $l^*(\hat{\pmb{\theta}})$모형의 $\sigma_a^2$가 0 으로 추정되었다는 것을 의미. \> 랜덤효과의 분산이 0으로 추정됨

-   귀무 모형과 풀 모형의 차이가 0.5이고 LRT는 현재 이 문제에선 자유도가 1인 카이제곱푼포를 따른다. \> p-value는 0.05보다 크다. \> 귀무가설을 기각 할수 없다. \> 랜덤효과의 분산이 0이 아니라고 말하기 충분한 근거가 없다.

## 3.5

**(3.94)를 유도하고** $BP^0(a_i)$ 와 $BP^0(a_k)$의 공분산을 구하고 $BP^0(a_i)-a_i$의 분산을 구하라.

$BP^0(a_i)$는 식(3.93)에 나와있다 그것을 활용해 분산을 구해보자.

$$
BP^0(a_i) = \frac{n\sigma^2_a}{\sigma^2+n\sigma^2_a}(\bar{y}_{i.}-\bar{y}_{..})
$$

### $Var[BP^0(a_i)]$

-   $c:=\frac{n\sigma^2_a}{\sigma^2+n\sigma^2_a}$로 두고 계산해보자.

$$
Var[BP^0(a_i)]=Var[c(\bar{y}_{i.}-\bar{y}_{..})] = c^2 Var[\bar{y}_{i.}-\bar{y}_{..}]
$$

#### 1. $Var(\bar{y}_{i.})$

-   $y_{ij} = \mu + a_i + \beta x_j + \epsilon_{ij}$에서 random variable로 봐야 할건 $a_i,\epsilon_{ij}$이다.

그럼

$$Var(\bar{y}_{i.})=Var\left(a_i+\frac{1}{n}\sum^n_{j=1}\epsilon_{ij}\right)=\left(\sigma^2_a+\frac{\sigma^2}{n}\right)$$

#### 2. $Var(\bar{y}_{..})$

풀이는 비슷하다.

$$
Var(\bar{y}_{..})=Var\left(\frac{1}{m}\sum^m_{i=1}a_i + \frac{1}{mn}\sum^m_{i=1}\sum^n_{j=1}\epsilon_{ij} \right) = \frac{\sigma_a^2}{m} + \frac{\sigma^2}{mn}
$$

#### 3. $Cov(\bar{y}_{i.},\bar{y}_{..})$

-   구체적으로 보자면 $\epsilon$간에는 서로 독립이니 0이고, 동일한 $a_i$들의 경우만 보면된다.

$$
Cov\left(a_i, \frac{1}{m} \sum_k a_k\right)=\frac{1}{m} Cov\left(a_i, a_i+a_{k \neq i}\right)=\frac{1}{m} \sigma_a^2
$$

#### 4. So, $Var[\bar{y}_{i.}-\bar{y}_{..}]$

정리하면,

$$
\begin{aligned}
Var\left(\bar{y}_{i.}-\bar{y}_{. .}\right)
&=\underbrace{\left(\sigma_a^2+\frac{\sigma^2}{n}\right)}_{{Var}\left(\bar{y}_{i.}\right)}
+\underbrace{\left(\frac{\sigma_a^2}{m}+\frac{\sigma^2}{m n}\right)}_{{Var}\left(\bar{y}_{..}\right)}
-2 \underbrace{\left(\frac{1}{m}\left(\sigma_a^2+\frac{\sigma^2}{n}\right)\right)}_{{Cov}\left(\bar{y}_{i.}, \bar{y}_{..}\right)}\\
&=\left(1-\frac{1}{m}\right) \left(\sigma_a^2+\frac{\sigma^2}{n}\right)\\
\
\Rightarrow c^2 Var (\bar{y}_{i.}-\bar{y}_{..}) 
&= \frac{n^2(\sigma^2_a)^2}{(\sigma^2+n\sigma^2_a)^2} \left(1-\frac{1}{m}\right) \left(\sigma_a^2+\frac{\sigma^2}{n}\right)\\
&= \frac{n^2(\sigma^2_a)^2}{(\sigma^2+n\sigma^2_a)^2} \left(1-\frac{1}{m}\right)\left(\frac{n\sigma_a^2+\sigma^2}{n}\right)\\
&= \frac{n(\sigma^2_a)^2}{\sigma^2+n\sigma^2_a} \left(1-\frac{1}{m}\right)\\
\end{aligned}
$$

### $Cov[BP^0(a_i),BP^0(a_k)](i\neq k)$

비슷한 아이디어로,

$$
{Cov}\left[B P^0\left(a_i\right), B P^0\left(a_k\right)\right]=c^2 {Cov}\left(\bar{y}_{i.}-\bar{y}_{. .}, \bar{y}_{k.}-\bar{y}_{. .}\right)
$$

$$
\begin{aligned}
{Cov}\left(\bar{y}_{i .}-\bar{y}_{. .}, \bar{y}_{k.}-\bar{y}_{. .}\right)
&={Cov}\left(\bar{y}_{i.}, \bar{y}_{k.}\right)
-{Cov}\left(\bar{y}_{i.}, \bar{y}_{..}\right)
-{Cov}\left(\bar{y}_{k.}, \bar{y}_{. .}\right)
+{Var}\left(\bar{y}_{..}\right)\\
&= 0
-\frac{1}{m}\left(\sigma_a^2+\frac{\sigma^2}{n}\right)
-\frac{1}{m}\left(\sigma_a^2+\frac{\sigma^2}{n}\right)
+\frac{\sigma^2_a}{m}+\frac{\sigma^2}{mn}\\
&= \frac{1}{m} \left[-2\left(\sigma^2_a+\frac{\sigma^2}{n}\right)+\sigma^2_a+\frac{\sigma^2}{n}\right]\\
&= - \frac{1}{m}\left(\sigma^2_a+\frac{\sigma^2}{n}\right)\\
\Rightarrow & \quad -c^2\frac{1}{m}\left(\sigma^2_a+\frac{\sigma^2}{n}\right)\\
&= -\frac{n(\sigma^2_a)^2}{m(\sigma^2+n\sigma^2_a)}
\end{aligned}
$$

### $Var[BP^0(a_i)-a_i]$

위 방법들을 사용한 식 정리는 다음과 같다.

$$
\begin{aligned}
Var[BP^0(a_i)-a_i] &= E[(a_i-c(\bar{y}_{i.}-\bar{y}_{..}))^2]\\
&= Var\left(a_i\right)+c^2 Var\left(\bar{y}_{i .}-\bar{y}_{. .}\right)-2 c\ Cov\left(a_i, \bar{y}_{i .}-\bar{y}_{. .}\right)\\
&= \sigma_a^2+c^2\left(1-\frac{1}{m}\right)\left(\sigma_a^2+\frac{\sigma^2}{n}\right)-2 c\left(1-\frac{1}{m}\right) \sigma_a^2\\
&= \sigma_a^2 + c\left(1-\frac{1}{m}\right) \sigma_a^2 -2 c\left(1-\frac{1}{m}\right) \sigma_a^2\\
&= \sigma_a^2 \left[1-\left(1-\frac{1}{m}\right)c \right]
\end{aligned}
$$

## 3.6

$\hat{\mu}$ 와 $BP^0(a_i)$, $\hat{\beta}$ 와 $\bar{y}_{i.}$, $\hat{\beta}$ 와 $\bar{y}_{..}$의 공분산을 구하라

3개 모두 공분산이 0임을 보인다는 것은 직교한다는 의미이다. \> gpt에서 말한 건데 아직 이유는 모르겠음

-   우선, 모형은 $y_{ij} = \mu + a_i + \beta x_j + \varepsilon_{ij}$ 이러하고,

-   BP의 식은 $BP^0(a_i) = \frac{n\sigma^2_a}{\sigma^2+n\sigma^2_a}(\bar{y}_{i.}-\bar{y}_{..})$ 이러하다.

### $Cov(\hat{\mu},BP^0(a_i))$

-   $c : = \frac{n\sigma^2_a}{\sigma^2+n\sigma^2_a}$ 라고 상수를 정리하고 들어간다.

$$
\begin{aligned}
Cov(\hat{\mu},BP^0(a_i)) & = Cov(\bar{y}_{..} - \hat{\beta}\bar{x},\ c (\bar{y}_{i.}-\bar{y}_{..}))\\ 
& = c*Cov\left(\bar{y}_{..} - \frac{S_{xy}}{S_{xx}}\bar{x}, \ \bar{y}_{i.}-\bar{y}_{..}\right)\\
& = c*\left( Cov(\bar{y}_{..},\ \bar{y}_{i.}) - Var(\bar{y}_{..}) - \frac{S_{xy}}{S_{xx}}*Cov(\bar{x},\ \bar{y}_{i.}) +  \frac{S_{xy}}{S_{xx}}* Cov(\bar{x},\ \bar{y}_{..})\right)\\
\end{aligned}
$$

마지막 식에서 각 term마다 따로따로 확인을 해보자.

#### 1. $Cov(\bar{y}_{..},\ \bar{y}_{i.})$

-   공분산을 구하는 것이기에 결국 0으로 없어지는 $y_{ij}$에서 상수를 제외하고 표현한다.

$$
\begin{aligned}
Cov(\bar{y}_{..},\ \bar{y}_{i.}) & = Cov\left(\mu +\frac{1}{I}\sum^I_i a_i + \beta\ \bar{x} + \frac{1}{IJ} \sum_{i,j}\varepsilon_{ij},\ \mu + a_i + \beta\ \bar{x} + \frac{1}{J}\sum^J_j\varepsilon_{ij}\right)\\
& = Cov\left(\frac{1}{I}\sum^I_i a_i,\ a_i \right) + \frac{1}{IJ^2}J *Var\left(\varepsilon_{ij}\right)\\
& = \frac{1}{I}Cov\left(a_i+\cdots+a_I,\ a_i \right) + \frac{1}{IJ}Var(\varepsilon_{ij})\\
& = \frac{1}{I}Var(a_i) + \frac{1}{IJ}Var(\varepsilon_{ij})
\end{aligned}
$$

#### 2. $Var(\bar{y}_{..})$

$$
\begin{aligned}
Var(\bar{y}_{..}) & = Var\left(\mu +\frac{1}{I}\sum^I_i a_i + \beta\ \bar{x} + \frac{1}{IJ} \sum_{i,j}\varepsilon_{ij}\right) \\
& = \frac{1}{I^2}Var\left(\sum^I_i a_i\right) + \frac{1}{I^2 J^2}IJ*Var\left(\varepsilon_{ij} \right)\\
& = \frac{1}{I} Var(a_i) + \frac{1}{IJ} Var(\varepsilon_{ij})
\end{aligned}
$$

#### 3. $\frac{S_{xy}}{S_{xx}}*Cov(\bar{x},\ \bar{y}_{i.})$

-   우선, $S_{xy}$를 밑에서 전개해서 풀면 복잡하므로 여기서 먼저 언급하고 간다.

$$
\begin{aligned}
S_{xy} & = \sum^I_i \sum^J_j (x_j-\bar{x})(y_{ij}-\bar{y}_{..})\\
& = \sum^I_i \sum^J_j (x_j-\bar{x})\left(a_i - \frac{1}{I}\sum^I_i a_i + \beta(x_j - \bar{x}) + \varepsilon_{ij} - \frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij}\right)\\
\end{aligned}
$$

이제 천천히 전개해서 확인해보자.

-   직접 많은 $\varepsilon$들을 전개해서 공분산을 구하게 되면 밑에 식처럼 정리 할 수 있다. $\underbrace{}{}$부분들이 직접 전개해보면 알 수 있는 부분들이다.

$$
\begin{aligned}
\frac{S_{xy}}{S_{xx}}&*Cov(\bar{x},\ \bar{y}_{i.}) \\
& = \frac{\bar{x}}{S_{xx}}*Cov(S_{xy},\bar{y}_{i.}) \\ 
& = \frac{\bar{x}}{S_{xx}}*Cov\left(\sum^I_i \sum^J_j (x_j-\bar{x})\left(a_i - \frac{1}{I}\sum^I_i a_i + \varepsilon_{ij} - \frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij}\right),\ a_i + \frac{1}{J}\sum^J_j\varepsilon_{ij}\right) \\
& = \frac{\bar{x}}{S_{xx}}*Cov\left(\sum^J_j (x_j-\bar{x})\sum^I_i\left(a_i - \frac{1}{I}\sum^I_i a_i + \varepsilon_{ij} - \frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij}\right),\ a_i + \frac{1}{J}\sum^J_j\varepsilon_{ij}\right)\\
& = \frac{\bar{x}}{S_{xx}}*\left[\sum^J_j (x_j-\bar{x})Cov\left(\underbrace{\sum^I_i\left(a_i - \frac{1}{I}\sum^I_i a_i\right)}_{=\ 0},\ a_i\right) \right.\\
& \quad \quad \quad \quad \quad + \left. Cov\left(\sum^J_j (x_j-\bar{x})\sum^I_i\left(\varepsilon_{ij} - \frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij} \right),\ \frac{1}{J}\sum^J_j\varepsilon_{ij}\right)\right]\\
& = \frac{\bar{x}}{S_{xx}}*\left[0 + \underbrace{Cov\left(\sum^I_i \sum^J_j (x_j-\bar{x})\varepsilon_{ij},\ \frac{1}{J}\sum^J_j\varepsilon_{ij}\right)}_{= \sum^J_j (x_j-\bar{x})Var(\varepsilon)} \right. \\
& \quad \quad \quad \quad \quad\left. - \ Cov\left(\underbrace{\sum^J_j (x_j-\bar{x})}_{=\ 0}\sum^I_i\left(\frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij} \right),\ \frac{1}{J}\sum^J_j\varepsilon_{ij}\right) \right]\\
& = \frac{\bar{x}}{S_{xx}}*Var(\varepsilon) \underbrace{\sum^J_j (x_j-\bar{x})}_{= \ 0}\\
& = 0
\end{aligned}
$$

#### 4. $\frac{S_{xy}}{S_{xx}}* Cov(\bar{x},\ \bar{y}_{..})$

3번과 거의 비슷하다.

$$
\begin{aligned}
\frac{S_{xy}}{S_{xx}}&* Cov(\bar{x},\ \bar{y}_{..}) \\
& = \frac{\bar{x}}{S_{xx}}*Cov(S_{xy},\bar{y}_{..})\\
& = \frac{\bar{x}}{S_{xx}}*Cov\left(\sum^I_i \sum^J_j (x_j-\bar{x})\left(a_i - \frac{1}{I}\sum^I_i a_i + \varepsilon_{ij} - \frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij}\right),\ \frac{1}{I}\sum^I_i a_i + \frac{1}{IJ}\sum^I_i \sum^J_j\varepsilon_{ij}\right)\\
& = \frac{\bar{x}}{S_{xx}}*\left[\sum^J_j (x_j-\bar{x})Cov\left(\underbrace{\sum^I_i\left(a_i - \frac{1}{I}\sum^I_i a_i\right)}_{=\ 0},\ \frac{1}{I}\sum^I_i a_i\right) \right.\\
& \quad \quad \quad \quad \quad + \left. Cov\left(\sum^J_j (x_j-\bar{x})\sum^I_i\left(\varepsilon_{ij} - \frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij} \right),\ \frac{1}{IJ}\sum^I_i \sum^J_j\varepsilon_{ij}\right)\right]\\
& = \frac{\bar{x}}{S_{xx}}*\left[\underbrace{Cov\left(\sum^J_j (x_j-\bar{x})\sum^I_i\varepsilon_{ij} ,\ \frac{1}{IJ}\sum^I_i \sum^J_j\varepsilon_{ij}\right)}_{= I*Var(\varepsilon) \sum_j (x_j-\bar{x})}\right. \\
& \quad \quad \quad \quad \quad - \left. Cov\left(\underbrace{\sum^J_j (x_j-\bar{x})}_{=\ 0}\sum^I_i\left(\frac{1}{IJ}\sum^I_i \sum^J_j \varepsilon_{ij} \right),\ \frac{1}{IJ}\sum^I_i \sum^J_j\varepsilon_{ij}\right)\right]\\
& = I*Var(\varepsilon) \sum_j (x_j-\bar{x}) \\
& = 0 \\
\end{aligned}
$$

-   4개의 term을 합쳐서 구하면 결국 0이 된다.

### $Cov(\hat{\beta},\bar{y}_{i.})$

-   $Cov(\hat{\beta},\bar{y}_{i.}) = \frac{1}{S_{xx}}Cov\left(S_{xy},\bar{y}_{i.}\right)$ 이 부분은 이미 $Cov(\hat{\mu},BP^0(a_i))=0$임을 보일 때 중간과정으로 이미 들어가 있다.

-   결국 $Cov(\hat{\beta},\bar{y}_{i.})=0$이다.

### $Cov(\hat{\beta},\bar{y}_{..})$

-   이 또한 마찬가지로 $Cov(\hat{\mu},BP^0(a_i))=0$을 구할 때 중간과정으로 들어가 있다.

-   결국 $Cov(\hat{\beta},\bar{y}_{..})=0$이다.

# Random intercepts: Unbalanced Data Section

## 3.7

**식(3.99)와 (3.100)을 유도하라**

식의 위치는 Random intercepts: Unbalanced Data Section 중에서 ML estimatiors에 해당한다.

주어진 정보는 다음과 같다.

모형.

$$
\begin{aligned}
\mathrm{E}\left[\mathbf{y}_i \mid a_i\right] & =\mu \mathbf{1}_{n_i}+a_i \mathbf{1}_{n_i}+\beta \mathbf{x}_i \\
& =\mathbf{x}_i\left[\begin{array}{c}
\mu \\
\beta
\end{array}\right]+\mathbf{1}_{n_i} a_i \\
\\
\mathbf{X}_i & =\left[\begin{array}{ll}
\mathbf{1}_{n_i} & \mathbf{x}_i
\end{array}\right] .\\
\end{aligned}
$$

행렬표현

$$
\begin{gathered}
\mathrm{E}[\mathbf{y} \mid \mathbf{a}]=\mathbf{X}\left[\begin{array}{c}
\mu \\
\beta
\end{array}\right]+\mathbf{Z a} \\
\mathbf{X}=\left\{_c\left[\begin{array}{ll}
\mathbf{1}_{n_i} & \mathbf{x}_i
\end{array}\right]\right\}_{i=1}^m \quad \text { and } \quad \mathbf{Z}=\left\{_d{1}_{n_i}
\right\}_{i=1}^m .
\end{gathered}
$$

분산.

$$
\begin{aligned}
\mathbf{V}_i & =\sigma^2 \mathbf{I}_i+\sigma_a^2 \mathbf{J}_i \\
\mathbf{V}_i^{-1} & =\frac{1}{\sigma^2}\left(\mathbf{I}_i-\frac{\sigma_a^2}{\sigma^2+n_i \sigma_a^2} \mathbf{J}_i\right)=\frac{1}{\sigma^2}\left(\mathbf{I}_i-\tau_i \overline{\mathbf{J}}_i\right)
\end{aligned}
$$

### (3.99)식 유도

$$
\begin{aligned}
\mathbf{X}^{\prime} \mathbf{V}^{-1} & =\left\{_r\left[\begin{array}{c}
\mathbf{1}_i^{\prime} \\
\mathbf{x}_i^{\prime}
\end{array}\right]\right\} \frac{1}{\sigma^2}\left\{_d \mathbf{I}_i-\tau_i \overline{\mathbf{J}}_i\right\}\\
& =\left\{_r\left[\begin{array}{c}
\left(\tau_i / n_i \sigma_a^2\right) 1_i^{\prime} \\
\left(\mathbf{x}_i^{\prime}-\tau_i \bar{x}_i \cdot \mathbf{1}_i^{\prime}\right) / \sigma^2
\end{array}\right]\right\}\\
\\
\mathbf{X}^{\prime} \mathbf{V}^{-1} \mathbf{X}& =\mathbf{X}^{\prime} \mathbf{V}^{-1}\left\{_c\left[\begin{array}{ll}
\mathbf{1}_i & \mathbf{x}_i
\end{array}\right]\right\}
\end{aligned}
$$

-   직접 식을 전개해서 정리한 다음 식(3.99)처럼 표현해보자

우선 $X^\prime V^{-1}$부터

$$
\begin{aligned}
\mathbf{X}^\prime \mathbf{V}^{-1} & = \mathbf{X^\prime}\frac{1}{\sigma^2}\left(\mathbf{I}-\frac{\tau_i}{n_i}\mathbf{J}\right)\\
& = \frac{1}{\sigma^2}\mathbf{X^\prime}-\frac{\tau_i}{n_i \sigma^2}\mathbf{X}^\prime\mathbf{J}\\
& = \left\{_m\frac{1}{\sigma^2}\left[
\begin{array}{cccc}
1 & 1 & \ldots & 1 \\
x_{i 1} & x_{i 2} & \ldots & x_{i n_i}
\end{array}\right] - \frac{\tau_i}{n_i \sigma^2}\left[
\begin{array}{cccc}
n_i & n_i & \ldots & n_i\\
\Sigma_j x_{i j} & \Sigma_j x_{i j} & \ldots & \Sigma_j x_{i j}
\end{array}\right]\right\}\\ 
& = \left\{_m\frac{1}{\sigma^2}\left[
\begin{array}{cccc}
1-\tau_i& 1-\tau_i & \ldots & 1-\tau_i \\
x_{i 1} - \tau_i \bar{x}_{i.} & x_{i 2} - \tau_i \bar{x}_{i.} & \ldots & x_{i n_i} - \tau_i \bar{x}_{i.}
\end{array}\right] \right\}\\
& = \left\{_m\frac{1}{\sigma^2}\left[
\begin{array}{cccc}
\frac{\sigma^2}{n_i \sigma^2_a}\tau_i & \frac{\sigma^2}{n_i \sigma^2_a}\tau_i & \ldots & \frac{\sigma^2}{n_i \sigma^2_a}\tau_i \\
x_{i 1} - \tau_i \bar{x}_{i.} & x_{i 2} - \tau_i \bar{x}_{i.} & \ldots & x_{i n_i} - \tau_i \bar{x}_{i.}
\end{array}\right] \right\}\\
& = \left\{_m\left[
\begin{array}{c}
(\tau_i/n_i \sigma^2_a) \mathbf{1}^\prime_i \\
(\mathbf{x}_{i}^\prime - \tau_i \bar{x}_{i.} \mathbf{1}_i^\prime)/\sigma^2
\end{array}\right] \right\}\\
\end{aligned}
$$

그 다음 $\mathbf{X}^\prime\mathbf{V}^{-1}\mathbf{X}$

$$
\begin{aligned}
\mathbf{X}^\prime\mathbf{V}^{-1}\mathbf{X} & = \left\{_m\frac{1}{\sigma^2}\left[
\begin{array}{cccc}
\frac{\sigma^2}{n_i \sigma^2_a}\tau_i & \frac{\sigma^2}{n_i \sigma^2_a}\tau_i & \ldots & \frac{\sigma^2}{n_i \sigma^2_a}\tau_i \\
x_{i 1} - \tau_i \bar{x}_{i.} & x_{i 2} - \tau_i \bar{x}_{i.} & \ldots & x_{i n_i} - \tau_i \bar{x}_{i.}
\end{array}\right] \left[
\begin{array}{ccc}
1 & x_{i1} \\
1 & x_{i2} \\
\vdots & \vdots \\
1 & x_{in_i} \\
\end{array}\right]\right\}\\
& = \left\{_m\left[
\begin{array}{cc}
\tau_i/\sigma^2_a & \tau_i\bar{x}_{i.}/\sigma^2_a \\
n_i \bar{x}_{i.}(1 - \tau_i)/\sigma^2 & (\Sigma_j x_{i j}^2 - \tau_i n_i\bar{x}^2_{i.})/\sigma^2
\end{array}\right]\right\}\\
& = \frac{1}{\sigma^2_a}\left[
\begin{array}{cc}
\Sigma_i\tau_i & \Sigma_i\tau_i\bar{x}_{i.} \\
\Sigma_i\bar{x}_{i.}\tau_i & \Sigma_i(\Sigma_j x_{i j}^2 - n_i\bar{x}^2_{i.}+n_i\bar{x}_{i.}^2(1- \tau_i))\sigma^2_a/\sigma^2
\end{array}\right] \\
\\
& \quad \quad \because \text{add,subtract } \Sigma_i n_i\bar{x}^2_{i.}/\sigma^2 \text{in (2,2) element} \\
\\
& = \frac{1}{\sigma^2_a}\left[
\begin{array}{cc}
\Sigma_i\tau_i & \Sigma_i\tau_i\bar{x}_{i.} \\
\Sigma_i\bar{x}_{i.}\tau_i & \frac{\sigma^2_a}{\sigma^2}\text{SSE}_{xx}+\Sigma_i \tau_i \bar{x}^2_{i.}
\end{array}\right] \quad (3.99)\\
& \quad \quad \because \text{SSE}_{xx} = \sum_i\left(\sum_j x_{ij}^2-n_i \bar{x}^2_{i.}\right) = \sum_{i,j}(x_{ij}-\bar{x}_{i.})^2
\end{aligned}
$$

### (3.100)식 유도

$$
\begin{aligned}
\mathbf{X}^\prime \mathbf{V}^{-1}\mathbf{y} & = \left\{_m\frac{1}{\sigma^2}\left[
\begin{array}{cccc}
\frac{\sigma^2}{n_i \sigma^2_a}\tau_i & \frac{\sigma^2}{n_i \sigma^2_a}\tau_i & \ldots & \frac{\sigma^2}{n_i \sigma^2_a}\tau_i \\
x_{i 1} - \tau_i \bar{x}_{i.} & x_{i 2} - \tau_i \bar{x}_{i.} & \ldots & x_{i n_i} - \tau_i \bar{x}_{i.}
\end{array}\right] \left[
\begin{array}{c}
y_{i1}\\ y_{i2}\\ \vdots\\ y_{in_i}
\end{array}\right]\right\}\\
& = \left\{_m
\left[\begin{array}{c}
\frac{1}{\sigma^2_a}\tau_i\bar{y}_{i.}\\ (\Sigma_jx_{ij}y_{ij} - \tau_i n_i \bar{x}_{i.} \bar{y}_{i.})/\sigma^2
\end{array}\right]\right\}\\
& = 
\left[\begin{array}{c}
\frac{1}{\sigma^2_a}\Sigma_i\tau_i\bar{y}_{i.}\\ \Sigma_i(\Sigma_jx_{ij}y_{ij} - n_i \bar{x}_{i.} \bar{y}_{i.} + n_i \bar{x}_{i.} \bar{y}_{i.}(1 -\tau_i ))/\sigma^2 
\end{array}\right]\\
& = \frac{1}{\sigma^2_a}\left[\begin{array}{c}
\Sigma_i\tau_i\bar{y}_{i.}\\ \frac{\sigma^2_a}{\sigma^2}\text{SSE}_{xy} + \Sigma_i\tau_i\bar{x}_{i.}\bar{y}_{i.}
\end{array}\right]\\
& \quad \quad \because \text{SSE}_{xy} = \sum_i\left(\sum_j x_{ij}y_{ij}-n_i \bar{x}_{i.}\bar{y}_{i.}\right) = \sum_{i,j}(x_{ij}-\bar{x}_{i.})(y_{ij}-\bar{y}_{i.})
\end{aligned}
$$

## 3.8

**식 (3.102)를 이용해 식 (3.106)의** $\hat{\mu}$을 유도하기

$$
\begin{aligned}
{\left[\begin{array}{c}
\hat{\mu} \\
\hat{\beta}
\end{array}\right]=} & \left(\mathbf{X}^{\prime} \mathbf{V}^{-1} \mathbf{X}\right)^{-1} \mathbf{X}^{\prime} \mathbf{V}^{-1} \mathbf{y} \\
= & \frac{\sigma_a^2}{|\mathbf{B}|}\left[\begin{array}{cc}
\frac{\sigma_a^2}{\sigma^2} \mathrm{SSE}_{x x}+\Sigma \tau_i \bar{x}_{i\cdot}^2 & -\Sigma \tau_i \bar{x}_{i\cdot} \\
-\Sigma \tau_i \bar{x}_{i\cdot} & \Sigma \tau_i
\end{array}\right] \times
\left[\begin{array}{c} 
\Sigma \tau_i \bar{y}_{i\cdot} / \sigma_a^2 \\
\mathrm{SSE}_{xy} / \sigma^2+\Sigma \tau_i \bar{x}_{i\cdot} \bar{y}_{i\cdot} / \sigma_a^2
\end{array}\right] \quad \quad (3.102)\\
\\
&\text{where}\quad|\mathbf{B}|= p r-q^2=\sum_i \tau_i\left(\frac{\sigma_a^2}{\sigma^2} \operatorname{SSE}_{x x}+\sum_i \tau_i \bar{x}_{i.}^2-\frac{\left(\Sigma \tau_i \bar{x}_{i.}\right)^2}{\Sigma \tau_i}\right) 
\end{aligned}
$$

-   차근차근 밟아보자

### $|\mathbf{B}|$

$$
\begin{aligned}
|\mathbf{B}| & = \sum_i \tau_i\left(\frac{\sigma_a^2}{\sigma^2} \operatorname{SSE}_{x x}+\sum_i \tau_i \bar{x}_{i.}^2-\frac{\left(\Sigma \tau_i \bar{x}_{i.}\right)^2}{\Sigma \tau_i}\right)\\
& = \sum_i \tau_i \left(\frac{\sigma_a^2}{\sigma^2}\mathrm{SSE}_{x x}+\mathrm{WSSA}_{x x}\right)
\end{aligned}
$$

-   $\frac{\sigma_a^2}{\sigma^2}\mathrm{SSE}_{x x}+\mathrm{WSSA}_{x x}$가 분모에 있으니 약분되서 $\tilde{y}_{..}$로 나올 수 있게 유도한다.

### $\tilde{y}_{..}$

-   $\hat{\mu}$의 분자 부분과 분모의 $\Sigma\tau_i$부분을 같이 보고 식을 전개해 보자.

$$
\begin{aligned}
& \frac{1}{\Sigma\tau_i}\sigma_a^2 \left[\frac{\sigma_a^2}{\sigma^2}\frac{\Sigma\tau_i \bar{y}_{i.}}{\sigma_a^2}\text{SSE}_{xx} + \frac{1}{\sigma_a^2}\Sigma\tau_i\bar{x}^2_{i.}\ \Sigma\tau_i\bar{y}_{i.} - \frac{1}{\sigma^2}\text{SSE}_{xy}\Sigma\tau_i\bar{x}_{i.} - \frac{1}{\sigma_a^2}\Sigma\tau_i\bar{x}_{i.}\ \Sigma\tau_i\bar{x}_{i.}\bar{y}_{i.}\right]\\
& = \frac{\sigma_a^2}{\sigma^2}\frac{\Sigma\tau_i \bar{y}_{i.}}{\Sigma\tau_i}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}^2_{i.}\ \frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i} - \cdots
\end{aligned}
$$

-   여기서 앞에 2개의 항만 확인해보자.

-   $\text{WSSA}_{xx}$의 형태를 맞춘다.

$$
\begin{aligned}
& \frac{\sigma_a^2}{\sigma^2}\frac{\Sigma\tau_i \bar{y}_{i.}}{\Sigma\tau_i}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}^2_{i.}\ \frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i}\\
& = \frac{\sigma_a^2}{\sigma^2}\frac{\Sigma\tau_i \bar{y}_{i.}}{\Sigma\tau_i}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}^2_{i.}\ \frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i} - \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i} + \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i}\\
& = \left[\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}^2_{i.}\ - \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\right]\frac{\Sigma\tau_i \bar{y}_{i.}}{\Sigma\tau_i} + \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i}\\
& = \left[\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \text{WSSA}_{xx}\right]\tilde{y}_{..} + \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i}
\end{aligned}
$$

-   약분하면 앞부분은 $\tilde{y}_{..}$만 남고 약분되고, 뒷부분은 그래도 남아서 다른 부분에 사용한다.

### $\hat\beta\ \tilde{x}_{..}$

-   남는 항과 이전에 만들고 남은 항도 가져와서 비슷하게 해본다.

$$
\begin{aligned}
& - \frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xy}\frac{\Sigma\tau_i\bar{x}_{i.}}{\Sigma\tau_i} - \frac{\Sigma\tau_i\bar{x}_{i.}}{\Sigma\tau_i}\ \Sigma\tau_i\bar{x}_{i.}\bar{y}_{i.} + \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i}\\
& = -\left[\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xy} + \Sigma\tau_i\bar{x}_{i.}\bar{y}_{i.} - \frac{\Sigma\tau_i\bar{x}_{i.}\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i}\right] \frac{\Sigma\tau_i\bar{x}_{i.}}{\Sigma\tau_i}\\
& = -\left[\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xy} + \text{WSSA}_{xy}\right] \tilde{x}_{..}\\
\\
& \Rightarrow -\hat\beta \tilde{x}_{..}
\end{aligned}
$$

-   이렇게 두 부분을 합치면 식 (3.106)$\mu$추정식과 같이 나오는 것을 확인할 수 있다.

## 3.9

**식(3.104),(3.106)의** $\hat\beta,\ \hat\mu$가 불편추정량인 것을 보여라

-   식(3.104)의 $\hat\beta$이 불편추정량인지 보여보자.

$$
\begin{aligned}
\hat\beta & = \frac{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x y}+\mathrm{WSSA}_{x y}}{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x x}+\mathrm{WSSA}_{x x}}\\
\\
\text{SSE}_{xy} & = \sum_{i,j}(x_{ij}-\bar{x}_{i.})(y_{ij}-\bar{y}_{i.})\\
& = \sum_{i,j}(x_{ij}-\bar{x}_{i.})(\beta(x_{ij}-\bar{x}_{i.})+(\varepsilon_{ij}-\bar\varepsilon_{i.}))\\
& = \beta\sum_{i,j}(x_{ij}-\bar{x}_{i.})^2 + \sum_{i,j}(x_{ij}-\bar{x}_{i.})(\varepsilon_{ij}-\bar\varepsilon_{i.})\\
& = \beta\ \text{SSE}_{xx} + \sum_{i,j}(x_{ij}-\bar{x}_{i.})\varepsilon_{ij}\\
E(\text{SSE}_{xy}) & = \beta\ \text{SSE}_{xx}+ \sum_{i,j}(x_{ij}-\bar{x}_{i.})E(\varepsilon_{ij})\\
& = \beta\ \text{SSE}_{xx}\\
\\
\text{WSSA}_{xy} & = \sum_i \tau_i \bar{x}_{i.}\bar{y}_{i.} - \frac{\Sigma_i \tau_i \bar{x}_{i.}\Sigma_i \tau_i \bar{y}_{i.}}{\Sigma_i \tau_i}\\
& = \sum_i \tau_i \bar{x}_{i.}(\mu + a_i + \beta \bar{x}_{i.} + \bar{\varepsilon}_{i.}) - \frac{\Sigma_i \tau_i \bar{x}_{i.}\Sigma_i \tau_i (\mu + a_i + \beta \bar{x}_{i.} + \bar{\varepsilon}_{i.})}{\Sigma_i \tau_i}\\
E(\text{WSSA}_{xy}) & = \sum_i \tau_i \bar{x}_{i.}(\mu + \beta \bar{x}_{i.}) - \frac{\Sigma_i \tau_i \bar{x}_{i.}\Sigma_i \tau_i (\mu + \beta \bar{x}_{i.})}{\Sigma_i \tau_i}\\
& = \sum_i \tau_i \bar{x}_{i.}\mu + \beta \sum_i \tau_i \bar{x}_{i.}^2 - \frac{\Sigma_i \tau_i \bar{x}_{i.}}{\Sigma_i \tau_i}(\sum_i \tau_i \mu + \beta \sum_i \tau_i \bar{x}_{i.})\\
& = \beta\left(\sum_i \tau_i \bar{x}^2_{i.} - \frac{(\Sigma_i \tau_i \bar{x}_{i.})^2}{\Sigma_i \tau_i}\right) + \mu \left(\sum_i \tau_i \bar{x}_{i.} - \sum_i \tau_i \bar{x}_{i.}\right)\\
& = \beta\ \text{WSSA}_{xx}
\\
\\
E(\hat\beta) & = E\left(\frac{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x y}+\mathrm{WSSA}_{x y}}{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x x}+\mathrm{WSSA}_{x x}} \right)\\
& = \frac{E\left(\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x y}+\mathrm{WSSA}_{x y}\right)}{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x x}+\mathrm{WSSA}_{x x}} \\
& = \frac{\beta\left(\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x x}+\mathrm{WSSA}_{xx}\right)}{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x x}+\mathrm{WSSA}_{x x}}\\
& = \beta
\end{aligned}
$$

-   $\hat\mu$도 불편추정량인지 보이자.

$\hat\beta$를 보였으니 간단하다.

$$
\begin{aligned}
\hat\mu & = \tilde{y}_{..} - \hat\beta\ \tilde{x}_{..}\\
& = \frac{\Sigma \tau_i\bar{y}_{i.}}{\Sigma \tau_i} - \hat\beta \tilde{x}_{..}\\
& = \frac{\Sigma\tau_i(\mu + a_i + \beta\bar{x}_{i.}+\bar{\varepsilon}_{i.})}{\Sigma \tau_i} - \hat\beta \tilde{x}_{..}\\
E(\hat\mu) & = \frac{\Sigma\tau_i(\mu + \beta\bar{x}_{i.})}{\Sigma \tau_i} - \beta \tilde{x}_{..}\\
& = \mu + \beta \underbrace{\frac{\Sigma \tau_i\bar{x}_{i.}}{\Sigma \tau_i}}_{=\ \tilde{x}_{..}} - \beta \tilde{x}_{..}\\
& = \mu
\end{aligned}
$$

## 3.10

**식(3.104),(3.106)에서** $n_i = n\ \forall i$라 두고 식을 정리하기

-   $n_i = n\ \forall i$라 둔다면, Balanced Data가 된다.

-   그럼, 이미 정답을 알고 있으니 그 형태에 맞게 식을 정리해보자.

$n_i = n\ \forall i$로 둔다면, 일부 식의 표현이 다음과 같이 달라진다.

$$
\begin{aligned}
\tau_i = \frac{n_i \sigma^2_a}{\sigma^2 + n_i \sigma^2_a} & \to \tau = \frac{n \sigma^2_a}{\sigma^2 + n \sigma^2_a}\\
\tilde{x}_{..} = \frac{\Sigma_i\tau_i \bar{x}_{i.}}{\Sigma_i\tau_i} & \to \tilde{x}_{..} = \frac{m\tau \bar{x}_{..}}{m\tau} = \bar{x}_{.} \\
\tilde{y}_{..} = \frac{\Sigma_i\tau_i \bar{y}_{i.}}{\Sigma_i\tau_i} & \to \tilde{y}_{..} = \frac{m\tau \bar{y}_{..}}{m\tau} = \bar{y}_{..} \\
\end{aligned}
$$

::: callout-warning
Balanced Data 와 Unbalanced Data 의 Notation이 다르기에 단순히 $j$부분을 제거하면 된다고 생각하면 안된다.

$j$를 제거하지 않고 $i$부분을 제거하는 데 이유는 각 그룹마다 갯수가 $n$으로 동일하기에 필요가 없어진다. 그냥 $m$번만 곱해주면 된다.

혼동되는 부분이 많기에 여기서 Notation의 변화를 자세히 보고 가길 바란다.
:::

그럼 대입해보자.

#### $\hat{\beta}$

$$
\begin{aligned}
\hat\beta & = \frac{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x y}+\mathrm{WSSA}_{x y}}{\left(\sigma_a^2 / \sigma^2\right) \mathrm{SSE}_{x x}+\mathrm{WSSA}_{x x}}\\
& = \frac{(\sigma^2_a/\sigma^2)\Sigma_{i,j}(x_{ij}-\bar{x}_{i.})(y_{ij}-\bar{y}_{i.})+\Sigma_i\tau_i(\bar{x}_{i.}-\tilde{x}_{..})(\bar{y}_{i.}-\tilde{y}_{..})}{(\sigma^2_a/\sigma^2)\Sigma_{i,j}(x_{ij}-\bar{x}_{i.})^2 + \Sigma_i\tau_i(\bar{x}_{i.}-\tilde{x}_{..})^2}\\
& = \frac{(\sigma^2_a/\sigma^2)\Sigma_{j}m(x_{j}-\bar{x}_{.})(\bar{y}_{.j}-\bar{y}_{..})+\tau \Sigma_j(x_{j}-\bar{x}_{.})(\bar{y}_{.j}-\bar{y}_{..})}{(\sigma^2_a/\sigma^2)\Sigma_{j}m(x_{j}-\bar{x}_{.})^2 + \tau \Sigma_j(x_{j}-\bar{x}_{.})^2}\\
& = \frac{(\sigma^2_a/\sigma^2)m\Sigma_{j}(x_{j}-\bar{x}_{.})(\bar{y}_{.j}-\bar{y}_{..})+\tau m\text{S}_{xy}}{(\sigma^2_a/\sigma^2)m\Sigma_{j}(x_{j}-\bar{x}_{.})^2 + \tau m \text{S}_{xx}}\\
& = \frac{(\sigma^2_a/\sigma^2)\text{S}_{xy}+\tau \text{S}_{xy}}{(\sigma^2_a/\sigma^2)\text{S}_{xx} + \tau \text{S}_{xx}}\\
& = \frac{[(\sigma^2_a/\sigma^2)+\tau]\text{S}_{xy}}{[(\sigma^2_a/\sigma^2) + \tau]\text{S}_{xx}} = \frac{\text{S}_{xy}}{\text{S}_{xx}}\\
\end{aligned}
$$

#### $\hat{\mu}$

$$
\begin{aligned}
\hat{\mu} & = \tilde{y}_{..} - \hat{\beta}\tilde{x}_{..}\\
& = \frac{\Sigma\tau_i\bar{y}_{i.}}{\Sigma\tau_i} - \hat{\beta}\frac{\Sigma\tau_i\bar{x}_{i.}}{\Sigma\tau_i}\\
& = \frac{m\tau\bar{y}_{..}}{m\tau} - \hat{\beta}\frac{m\tau\bar{x}_{..}}{m\tau}\\
& = \bar{y}_{..} - \hat{\beta}\bar{x}_{..}
\end{aligned}
$$

## 3.11

$\text{var}(\hat\beta),\ \text{var}(\hat\mu)$를 식(3.107),(3.108)와 같이 유도하라

-   우선 두 추정량의 분산을 구해야 하니 행렬로 접근한다.

$$
\begin{aligned}
\pmb{\hat\theta} = \left[\begin{array}{c} \hat\mu \\
\hat\beta\end{array}\right] & = (\pmb{X}^\top \pmb{V}^{-1}\pmb{X})^{-1}\pmb{X}^\top \pmb{V}^{-1} \pmb{y} \\
\text{var}(\pmb{\hat\theta}) & = (\pmb{X}^\top \pmb{V}^{-1}\pmb{X})^{-1}\pmb{X}^\top \pmb{V}^{-1} \text{var}(\pmb{y})\pmb{V}^{-1} \pmb{X}^\top (\pmb{X}^\top \pmb{V}^{-1}\pmb{X})^{-1}\\
& = (\pmb{X}^\top \pmb{V}^{-1}\pmb{X})^{-1}\pmb{X}^\top \pmb{V}^{-1} \pmb{V}\ \pmb{V}^{-1} \pmb{X}^\top (\pmb{X}^\top \pmb{V}^{-1}\pmb{X})^{-1}\\
& = (\pmb{X}^\top \pmb{V}^{-1}\pmb{X})^{-1}\\
& = \frac{\sigma_a^2}{|\pmb{B}|}\left[\begin{array}{cc}
\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}_{i.}^2 & -\Sigma\tau_i \bar{x}_{i.} \\
-\Sigma\tau_i \bar{x}_{i.} & \Sigma \tau_i\\
\end{array}\right]\\
& \text{where }\ |\pmb{B}| = \Sigma \tau_i \left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \text{WSSA}_{xx}\right)
\end{aligned}
$$

-   $\text{var}(\pmb{\hat\theta})$는 분산공분산 행렬이기에 $\text{var}(\hat\beta)$는 (2,2)항, $\text{var}(\hat\mu)$는 (1,1)항이다.

### $\text{var}(\hat\beta)$

$$
\begin{aligned}
\text{var}(\hat\beta) & = \frac{\sigma_a^2\ \Sigma\tau_i}{\Sigma\tau_i\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} +  \text{WSSA}_{xx}\right)} \\
& = \frac{1}{\frac{1}{\sigma_a^2}\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx}+\text{WSSA}_{xx}\right)} \\
& = \frac{1}{\frac{\text{SSE}_{xx}}{\sigma^2} + \frac{\text{WSSA}_{xx}}{\sigma_a^2}} 
\end{aligned}
$$

### $\text{var}(\hat\mu)$

$$
\begin{aligned}
\text{var}(\hat\mu) & = \frac{\sigma_a^2\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}_{i.}^2\right)}{\Sigma\tau_i\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx}+\text{WSSA}_{xx}\right)}\\
& = \frac{\sigma_a^2\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}_{i.}^2 - \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}+\frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\right)}{\Sigma\tau_i\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx}+\text{WSSA}_{xx}\right)}\\
& = \frac{\frac{\sigma_a^2}{\Sigma\tau_i}\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \Sigma\tau_i\bar{x}_{i.}^2 - \frac{(\Sigma\tau_i\bar{x}_{i.})^2}{\Sigma\tau_i}\right)+\sigma_a^2\frac{(\Sigma\tau_i\bar{x}_{i.})^2}{(\Sigma\tau_i)^2}}{\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx}+\text{WSSA}_{xx}\right)}\\
& = \frac{\frac{\sigma_a^2}{\Sigma\tau_i}\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx} + \text{WSSA}_{xx}\right)+\sigma_a^2\tilde{x}_{..}^2}{\left(\frac{\sigma_a^2}{\sigma^2}\text{SSE}_{xx}+\text{WSSA}_{xx}\right)}\\
& = \frac{\sigma_a^2}{\Sigma\tau_i} + \tilde{x}_{..}^2 \text{var}(\hat{\beta})
\end{aligned}
$$

# Logistic with random intercepts.

## 3.12

$x$가 0 또는 1을 갖는 binary data 라면, 식(3.116)의 $\alpha$와 $\beta$의 MLE를 구하라

$$
\begin{aligned}
&\sum_{i=1}^n y_i=\sum_{i=1}^n \frac{1}{1+e^{-(\hat{\alpha}+\hat{\beta} x_i)}}\\
&\sum_{i=1}^n x_i y_i=\sum_{i=1}^n \frac{x_i}{1+e^{-(\hat{\alpha}+\hat{\beta} x_i)}} \quad \quad (3.116)
\end{aligned}
$$

-   일반적인 로지스틱 모형에서는 $\alpha,\beta$는 numerical 하게 구해야하는데, 여기선 $x$가 이진수 이니까 구할 수 있다고 저자는 말하고 있다.

#### 정의

-   변수에 정의를 먼저 해보자

$$
\begin{aligned}
& n_0 : x_i=0 \scriptsize\text{ 인 갯수} \\
& n_1 : x_i=1 \scriptsize\text{ 인 갯수} \\
& y_0 = \Sigma_{i|x=0}\ y_i : x_i\scriptsize\text{ 가 0일 때 } \normalsize y_i  \scriptsize\text{의 총합}\\
& y_1 = \Sigma_{i|x=1}\ y_i : x_i\scriptsize\text{ 가 1일 때 } \normalsize y_i  \scriptsize\text{의 총합}\\
\end{aligned}
$$

-   그럼 $Y=1$일 확률을, 조건부로 정의할 수 있다.

$$
\begin{aligned}
& p_0 = P(Y=1|x=0) = \frac{1}{1+e^{-\alpha}}\\
& p_1 = P(Y=1|x=1) = \frac{1}{1+e^{-(\alpha+\beta)}}\\
\end{aligned}
$$

#### 정리

$$
\begin{aligned}
\Sigma y_i & = \Sigma_{i|x=0}\ y_i + \Sigma_{i|x=1}\ y_i \\
& = n_0 p_0 + n_1 p_1 \\
& = n_0 \frac{1}{1+e^{-\alpha}} + n_1 \frac{1}{1+e^{-(\alpha+\beta)}} \\
\\
& \Rightarrow y_0 = n_0 \frac{1}{1+e^{-\alpha}} \\
& \Rightarrow 1+e^{-\alpha} = \frac{n_0}{y_0} \\
& \Rightarrow e^{-\alpha} = \frac{n_0 - y_0}{y_0} \\
& \Rightarrow \ \therefore \ \alpha = log\left(\frac{y_0}{n_0-y_0}\right) \\
\\
& \Rightarrow \ \therefore \ \beta = log\left(\frac{y_1(n_0-y_0)}{y_0(n_1-y_1)}\right) \\
\end{aligned}
$$

## 3.13

$y_i=1 \quad$ if $x_i>d, \quad y_i=0 \quad$ if $x_i<d$이러한 임계값 $d$가 존재한다면 로그가능도 함수의 $\beta$가 유한하지 않음을 보여라

$$
l=\log L=\sum_{i=1}^n y_i\left(\alpha+\beta x_i\right)-\log \left(1+e^{\alpha+\beta x_i}\right) \quad \quad (3.113)
$$

#### $x_i > d \ (y_i = 1)$ 인 경우

-   $x_i$가 임의의 숫자 $d$보다 커서 무조건 $y_i=1$이 될라면 $\alpha + \beta x_i$가 극단적으로 $+\infty$로 가야한다.

-   그렇게 되면 식(3.113) 로그 가능도함수가 다음과 같이 된다.

$$
\sum_{i=1}^n y_i\left(\alpha+\beta x_i\right)-\log \left(1+e^{\alpha+\beta x_i}\right) \to \sum 1*\infty - 0 = +\infty
$$

-   즉, $\alpha$가 유한할 때, $\beta$는 무조건 발산한다.

#### $x_i < d \ (y_i = 0)$ 인 경우

-   반대로 무조건 $y_i$가 0이 될라면 $\alpha + \beta x_i$가 극단적으로 $-\infty$로 가야한다.

-   결론 이 부분도 로그 가능도 함수에 만족하게 끔 $\alpha,\beta$를 조정하다보면 $\beta$는 무조건 발산하게 된다.

## 3.14

**모형(3.109)에서** $\beta=0$일 때, $\hat{\alpha}$의 추정량을 구해보기

$$
\mathrm{E}\left[y_i\right]=\pi\left(x_i\right)=\frac{1}{1+e^{-\left(\alpha+\beta x_i\right)}} \quad \quad (3.109)
$$

-   가능도함수부터 구해서 식을 정리한다.

$$
\begin{aligned}
L & = \prod^n_{i=1}\pi(x_i)^{y_i}(1-\pi(x_i))^{1-y_i}\\
& = \prod^n_{i=1}\left(\frac{1}{1+e^{-\alpha}}\right)^{y_i}\left(1-\frac{1}{1+e^{-\alpha}}\right)^{1-y_i}\\
\\
l & = \sum_i -y_i\log(1+e^{-\alpha}) + (1-y_i)[-\alpha-\log(1+e^{-\alpha})]\\
& = \sum_i -\log(1+e^{-\alpha}) - (1-y_i)\alpha \\
\\
\frac{\partial \ l}{\partial \ \alpha} & = \sum_i \left(\frac{e^{-\alpha}}{1+e^{-\alpha}}-(1-y_i)\right) = 0 \\
& \Rightarrow n-n\bar{y} = n\frac{e^{-\alpha}}{1+e^{-\alpha}}\\
& \Rightarrow e^{\alpha} = \frac{\bar{y}}{1-\bar{y}} \\
& \Rightarrow \hat\alpha = \log\frac{\bar{y}}{1-\bar{y}}
\end{aligned}
$$

## 3.15 (책에 오류가 있음)
